services:
  sqlcoder:
    container_name: sqlcoder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/root/.local/share/instructlab/checkpoints:rw
      - ./logs:/workspace/logs
    environment:
      CUDA_HOME: /usr/local/cuda
      NVIDIA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["/entrypoint.sh"]
